import { Inter, Lato, Poppins } from "next/font/google";
import "./globals.css";

import { PrimeReactProvider, PrimeReactContext } from "primereact/api";
import { NextUIProvider } from "@nextui-org/react";
import { ChakraProvider } from "@chakra-ui/react";
import { ThemeProvider } from "@mui/material";
import theme from "@/components/theme";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        />
        {/* <!-- Font Awesome CSS --> */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        />
      </head>
      <body className={`${inter.className} dark bg-[#121212] w-full h-[100vh]`}>
        {
          <ThemeProvider theme={theme}>
            <ChakraProvider>{children}</ChakraProvider>
          </ThemeProvider>
        }
      </body>
    </html>
  );
}
